### ISSUE TITLE
Can't find app in menus after installing deb package

### ISSUE THREAD

**Issue by crilleengvall** [unindented/electron-installer-debian#107]
**What version of `electron-installer-debian` are you using?**
0.6.0

**What version of `node` and `npm` are you using?**
3.10.10

**What operating system are you using?**
Linux mint

**Can you compile the [example app](https://github.com/unindented/electron-installer-debian/tree/master/example) successfully?**
I can create packages and install the app. And after the app is installed i can find it in the menus.

**If not, paste here the output of the following commands:**

```
$ git clone https://github.com/unindented/electron-installer-debian.git
$ cd electron-installer-debian/example
$ DEBUG='electron-installer-debian' npm run build
```

**What did you do? Please include the configuration you are using for `electron-installer-debian`.**
I ran this after packaging the app into the release-builds folder
`electron-installer-debian --src release-builds/Electron\ tutorial\ app-linux-x64/ --arch amd64 --config debian.json`

my debian.json looks like this:
```
{
  "dest": "release-builds/installers/",
  "icon": "assets/icons/png/1024x1024.png",
  "bin": "",
  "categories": [
    "Utility"
  ],
  "lintianOverrides": [
    "changelog-file-missing-in-native-package"
  ]
}
```

**What did you expect to happen?**
That i could start the app from the menus after installation.

**What actually happened?**
I'm trying to build a debian package for this application:
https://github.com/crilleengvall/electron-tutorial-app
and write a tutorial about it. The debian package is created and i can install it.
But no app can be found in the menus. But i can start it from:
/usr/lib/electron-tutorial-app by running ./electron-tutorial-app

I have tried the suggestions in this issue but i can't seem to get it to work
https://github.com/unindented/electron-installer-debian/issues/19

The .desktop-file that is generated looks like this:
[Desktop Entry]
Name=Electron tutorial app
Comment=Application for electron tutorials
GenericName=Electron tutorial app
Exec=electron-tutorial-app %U
Icon=electron-tutorial-app
Type=Application
StartupNotify=true
Categories=Utility;

**Comment by fcastilloec** [comment]
This is not a bug but mainly a problem with your configuration. This question should be asked in the [community forums](https://github.com/electron/electron#community) and not filed as an issue. Nonetheless, here's my answer.
First, electron-packager uses the `productName` first when you don't specify `appname` to the cli, as it's stated [here](https://github.com/electron-userland/electron-packager#from-the-command-line)

> If appname is omitted, this will use the name specified by "productName" or "name" in the nearest package.json

So you will have a conflict when creating a link to the executable.
The second problem, is that your `debian.json` `bin` is blank, this should point to the executable created by `electron-packager`.

The proper way to fix this is passing `appname` to `electron-packager` and making `appname` be exactly what the `name` field in your `package.json` is, and removing the `bin` option from your `debian.json`.

An alternative, that it's not recommended since doesn't follow proper Debian naming guides, is to not pass `appname` (as you've been doing so far) and set the `bin` option in `debian.json` to `Electron tutorial app` (your `productName`). If you would have checked what `electron-packager` was creating, you would have seen that your executable name is `Electron tutorial app` (which doesn't follow proper Debian naming guideliness).

**Comment by crilleengvall** [comment]
Thank you @fcastilloec for the help. That solved it!
I wasn't aware that i should post this in the electron forum, i will do that from now on.

**Comment by malept** [comment]
@fcastilloec we should add a `SUPPORT.md` like [electron-installer-snap](https://github.com/electron-userland/electron-installer-snap/blob/master/SUPPORT.md).

**Comment by ferso** [comment]
Thank you @fcastilloec. You answered this no commented problem in almost every tutorial that i read.
