### ISSUE TITLE
Can I choose the name of the file I want to output?

### ISSUE THREAD

**Issue by Linbubin** [unindented/electron-installer-debian#93]
```
electron-installer-debian  v0.4.0
node v8.1.2
npm v5.2.0
system
Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux
```

I want to make xxx.deb, i do.
but the name is not my expectant.

my config is 
```
const defaults = {
      bin: 'testProduct',
      dest: 'dist/installers/debian',
      depends: ['libappindicator1', 'avahi-daemon'], 
      icon: 'build/assets/img/main.png', 
      categories: ['AudioVideo', 'Audio'], 
      section: 'sound',
      src: 'dist/testProduct-linux-x64',
      arch: 'amd64',
    };
```

```
~/Workspace/Web-App-Desktop/dist $ ls
installers  testProduct-linux-x64  Web-App-Desktop-linux-x64-1
```

when it complete， i can find `Web-App-Desktop_0.0.1_amd64.deb`，
but i want to get `testProduct_0.0.1_amd64.deb`.

```
~/Workspace/Web-App-Desktop/dist/installers $ ls -R
.:
debian

./debian:
Web-App-Desktop_0.0.1_amd64.deb
```

how can i do? or defaults write wrong?

the `Web-App-Desktop_0.0.1_amd64.deb` is include `testProduct-linux-x64`.

**Comment by Linbubin** [comment]
I know what's wrong.
the `electron-installer-debian` output filename is consist of `package.json inside defaults.src`,

`debFileName = package.name + '_' + package.version + '_' + defaults.arch + '.deb'`,

This is done automatically.
Can I determine the parameter by entering it?

**Comment by Linbubin** [comment]
i find the way, change defaults to ensure the output filename

`debFileName = package.name + '_' + package.version + '_' + defaults.arch + '.deb',`

```
const defaults = {
      name: 'outputname',
      version: 'outputversion',
      bin: 'testProduct',
      dest: 'dist/installers/debian',
      depends: ['libappindicator1', 'avahi-daemon'], 
      icon: 'build/assets/img/main.png', 
      categories: ['AudioVideo', 'Audio'], 
      section: 'sound',
      src: 'dist/testProduct-linux-x64',
      arch: 'amd64',
    };
```

:+1: 
I'm sorry to trouble you.

**Comment by dlhsiao** [comment]
Hello, I am also having this problem and haven't been able to fix it. 

`electron-installer-debian v^1.1.1
  node v11.14.0
  npm v5.2`

I want my app to be called the package.productName rather than the package.name, but I can't find a way to get electron-installer-debian to accept the different name. With electron-installer-windows, there's the options.exe field that I can set, but there doesn't seem to be an option similar to that for debian. 

package.json
`{
  "productName": "Pyret",
  "name": "code.pyret.org",
  "version": "0.0.0",`

debian.json
`{
  "options": {
    "productName": "Pyret",
    "name": "Pyret"
  },
  "dest": "release_builds/",
  "icon": "assets/icons/png/1024x1024.png",
  "categories": [
    "Education"
  ],
  "lintianOverrides": [
    "changelog-file-missing-in-native-package"
  ]
}`

This is the command I'm using:
`electron-installer-debian --src ./release_builds/Pyret-linux-x64/ --arch amd64 --config debian.json`

If I don't set the exectuableName for the electron-packager command, this is the error I get:
`Error: Error creating contents of package: Error creating binary symlink: could not find the Electron app binary at "release_builds/Pyret-linux-x64/code.pyret.org". You may need to re-bundle the app using Electron Packager's "executableName" option.
    at fs.pathExists.then.exists (/home/travis/build/dlhsiao/code.pyret.org/node_modules/electron-installer-common/src/installer.js:145:17) `Error: Error creating contents of package: Error creating binary symlink: could not find the Electron app binary at "release_builds/Pyret-linux-x64/code.pyret.org". You may need to re-bundle the app using Electron Packager's "executableName" option.\n    at fs.pathExists.then.exists (/home/travis/build/dlhsiao/code.pyret.org/node_modules/electron-installer-common/src/installer.js:145:17)``

Is there a way to have the application be called Pyret instead of code.pyret.org, and how do I do it?
