### ISSUE TITLE
Build amd x86_64 deb from armv7 device

### ISSUE THREAD

**Issue by kounelios13** [unindented/electron-installer-debian#95]
**What version of `electron-installer-debian` are you using?**
0.5.2
**What version of `node` and `npm` are you using?**
npm 5.4.0
**What operating system are you using?**
Ubuntu 17.04

**Can you compile the [example app](https://github.com/unindented/electron-installer-debian/tree/master/example) successfully?**

**If not, paste here the output of the following commands:**

```
$ git clone https://github.com/unindented/electron-installer-debian.git
$ cd electron-installer-debian/example
$ DEBUG='electron-installer-debian' npm run build
```

**What did you do? Please include the configuration you are using for `electron-installer-debian`.**
Hello.I am using electron-forge to package my app for ubuntu(which uses electron-installer-debian)
Now I want to package my app for my x86_x64 laptop using a raspberry pi .How can I do that?
Heres is my configuration inside package.json for electron-installer-debian:
```
"electronInstallerDebian": {
        "productName": "Ubuntu Graphical Service Manager",
        "name": "ugsm",
        "arch": "x86_64",
        "icon": "src/icons/ugsm256x256.png"
      },
```
**What did you expect to happen?**

**What actually happened?**

**Comment by fcastilloec** [comment]
If you're using `electron-forge` you should report the issue directly to them. I know they internally use this project to build the installer, but the issue is related to them and not this project.
Before you can create an installer, you need to package the app, `electron-forge` takes care of both steps. Your error might be related to the step of packaging the app. Try using `electron-packager` and with that output use `electron-installer-debian`.

**Comment by malept** [comment]
I'll just leave the answer here so there doesn't need to be an issue filed in Forge's issue tracker (questions should really be asked in the [community forums](https://github.com/electron/electron#community) anyway).

Forge overwrites `arch` for `electron-installer-debian`, because it needs to know the arch for Electron Packager too. So, you would need to run `electron-forge make --arch x64` on your rpi, and it will do the Right Thing:tm:.
